include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_print: warning

    avoid_relative_lib_imports: error
    prefer_relative_imports: error

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    avoid_relative_lib_imports: true
    prefer_relative_imports: true